language: node_js
node_js:
  - '12'
  - '11'
  - '10'
  - '8'
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
